#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Total Number of batman originator
graph_vlabel originator count
graph_category Freifunk
graph_args --base 1000 -l 0
graph_scale no
default.label default
default.info Number of active originator default segment
segment-01.label Segment-01
segment-01.info Number of active originator in segment 01
ssegment-02.label Segment-02
segment-02.info Number of active originator in segment 02
egment-03.label Segment-03
segment-03.info Number of active originator in segment 03

EOM
        exit 0;;
esac

printf "default.value "
expr `cat /sys/kernel/debug/batman_adv/bat0/originators | wc -l` - 8
printf "segment-02.value "
expr `cat /sys/kernel/debug/batman_adv/bat02/originators | wc -l` - 6
printf "segment-03.value "
expr `cat /sys/kernel/debug/batman_adv/bat03/originators | wc -l` - 6
